name: 'Cherry pick Release/candidate into develop'

on:
    pull_request:
        branches:
            - develop
        types:
            - closed

permissions:
    pull-requests: write

jobs:
    test-cherry-pick:
        runs-on: ubuntu-latest
        name: Test the cherry-pick action
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Cherry pick
              id: cherry-pick
              uses: ./
              with:
                  target-branch: 'main'
                  pr-title-suffix: 'üçí'
            - name: Get the output
              run:
                  echo "The created PR number is ${{ steps.cherry-pick.outputs.pr-number }}"
